substitutions:
  hostname: esp32-b9ace8

esphome:
  name: ${hostname}

esp32:
  variant: ESP32
  framework:
    type: esp-idf

# Enable logging
logger:

# Enable Home Assistant API
#api:
  #encryption:
    #key: !secret encryption_key
    # 
mqtt:
  broker: !secret mqtt_broker
  log_topic:
    topic: debug
    level: ERROR
  client_id: ${hostname}
  topic_prefix: HA

ota:
  - platform: esphome

# https://community.home-assistant.io/t/blink-how/307243/14
# Blink the blue LED
output:
  - platform: gpio
    pin:
      number: 2
      mode: output
    id: blueLED

interval:
  - interval: 1000ms
    then:
      - output.turn_on: blueLED
      - delay: 50ms
      - output.turn_off: blueLED

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: !secret fallback_ssid
    password: !secret fallback_password

captive_portal:
    